#!/bin/bash


### Desktop Enviroments (DE)
## KDE Plasma
#pacman -S plasma --noconfirm
## GNOME
#pacman -S gnome --noconfirm
## MATE
#pacman -S mate --noconfirm
## Xfce
#pacman -S xfce4 --noconfirm

### Display Manager (DM)
## SDDM
#pacman -S sddm --noconfirm
#systemctl enable sddm
## GDM
#pacman -S gdm --noconfirm
#systemctl enable gdm

